language: java
dist: precise

jdk:
  - oraclejdk8

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

addons:
   hosts:
       - travis
   hostname: travis

script: mvn clean test
